/*
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef ABSTRACT_SOCKET_HPP_
#define ABSTRACT_SOCKET_HPP_

#include <unistd.h>
#include <mutex>
#include <stdexcept>
#include <array>
#include <thread>

#include "abstract_system_socket.hpp"
#include "logger.hpp"

namespace net {

/** @brief Structure to avoid issues when giving buffers to AbstractSocket.
 *
 * This structure allows to avoid issues about templates when giving a buffer
 * to AbstractSocket. It is not meant to be directly used by the user.
 * The user must only use buffer(...).
 */
struct __buffer {
	/// Pointer to address holding data:
	void* ptr_;
	/// Size (in bytes) of data:
	std::size_t size_;
};

/**
 * @brief Function to pass a std::array to AbstractSocket
 */
template<std::size_t N>
inline __buffer buffer(std::array<char, N>& buf)
{
	return __buffer {reinterpret_cast<void*>(buf.data()), buf.size()};
}

/**
 * @brief Base abstract class for protocols.
 *
 * This is the base abstract class for protocols. Any supported protocol
 * must inherit from this class.
 */
class AbstractSocket {
public:
	/**
	 * @brief Read operation on the socket
	 *
	 * This function reads from the socket taking care of synchronization
	 * with any other asynchronous operations.
	 * @param buf Pointer where read data must be put
	 * @param size Size of data to be read
	 * @return Number of bytes actually read
	 * @exception runtime_error in case of too small buffer
	 *
	 * Example of usage:
	 * <code>
	 * 		std::array<char, 5> buf;
	 * 		AbstractSocket::read(net::buffer(b), 3);
	 * </code>
	 */
	inline int read (__buffer buf, std::size_t size){
		if (buf.size_ == 0 || size > buf.size_){
			DEBUG(ERROR, "Wrong buffer size!");
			throw std::runtime_error ("Wrong buffer size");
		}
		read_lock_.lock();
		int ret = socket_->read(buf.ptr_, size);
		read_lock_.unlock();
		return ret;
	}

	/**
	 * @brief Write operation on the socket
	 *
	 * This function writes to the socket taking care of synchronization
	 * with any other asynchronous operations.
	 * @param buf Pointer to data to be written
	 * @param size Size of data to be written
	 * @return Number of bytes actually written
	 * @exception runtime_error in case of too small buffer
	 *
	 * Example of usage:
	 * <code>
	 * 		std::array<char, 5> buf;
	 * 		AbstractSocket::write(net::buffer(b), 3);
	 * </code>
	 */
	inline int write (__buffer buf, std::size_t size){
		if (buf.size_ == 0 || size > buf.size_){
			DEBUG(ERROR, "Wrong buffer size!");
			throw std::runtime_error ("Wrong buffer size");
		}
		write_lock_.lock();
		int ret = socket_->write(buf.ptr_, size);
		write_lock_.unlock();
		return ret;

	}

	/**
	 * @brief Close the socket
	 *
	 * Method to close the socket. Currently, there is no mechanism
	 * to re-open a closed socket.
	 *
	 * @return true in case of success; false otherwise
	 */
	inline bool close(){
		return socket_->close();
	}

	/**
	 * @brief get the socket
	 *
	 * This method is used to let derived classes of AbstractSocket invoke
	 * specific protocol-dependent functions (e.g., accept()).
	 *
	 * @return the socket used by this instance of the class
	 */
	inline AbstractSystemSocket* getSocket(){
		return socket_.get();
	}

protected:
	/**
	 * @brief Constructor
	 *
	 * Constructor is protected because only derived classes
	 * can construct this class.
	 * @param the platform-dependent socket; this object is
	 * constructed by the derived class' constructor, afterwards it
	 * is managed (i.e., kept and deleted) by this class.
	 */
	AbstractSocket(AbstractSystemSocket* sock):
		socket_{sock} {}

	/**
	 * @brief Pointer to the platform-dependent socket
	 *
	 * The platform-dependent socket is created by deriverd
	 * class' constructor and then owned by this class. 
	 */
	std::unique_ptr<AbstractSystemSocket>  socket_;

private:
	/**
	 * @brief Thread for asynchronous read operations
	 */
	std::unique_ptr<std::thread> read_worker_;

	/**
	 * @brief Thread for asynchronous read operations
	 */
	std::unique_ptr<std::thread> write_worker_;

	/**
	 * @brief Mutex for synchronization with asynchronous read operations.
	 */
	std::mutex read_lock_;
	
	/**
	 * @brief Mutex for synchronization with asynchronous write operations.
	 */
	std::mutex write_lock_;
};

}

#endif // ABSTRACT_SOCKET_HPP_
