/*
 * Copyright (C) 2013 Evidence Srl - www.evidence.eu.com
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef LOGGER_HPP_
#define LOGGER_HPP_

#include <fstream>
#include <ostream>
#include <string>
#include <sstream>
#include <sys/time.h>
#include <mutex>


/**
 * \brief Macro to configure the logger.
 *
 * @param Base name of the file used for logging (e.g. "/tmp/myproject")
 * @param File severity level (i.e., OFF, ERROR, WARN, DEBUG)
 * @param Console severity level (i.e., OFF, ERROR, WARN, DEBUG)
 *
 * Example of configuration of the Logger: *
 * \code
 * 	DEBUG_CONF("outputfile", DEBUG, ERROR);
 * \endcode
 */
#define DEBUG_CONF(outputFile, \
		fileSeverityLevel, \
		screenSeverityLevel) { \
			net::Logger::getInstance().configure(outputFile, \
						fileSeverityLevel, \
						screenSeverityLevel); \
		}

/**
 * \brief Macro to print log messages.
 *
 * Example of usage of the Logger:
 * \code
 * 	DEBUG(DEBUG, "hello " << "world");
 * \endcode
 */
#define DEBUG(priority, msg) { \
	std::ostringstream __debug_stream__; \
	__debug_stream__ << msg; \
	net::Logger::getInstance().print(priority, __FILE__, __LINE__, \
			__debug_stream__.str()); \
	}


/**
 * \brief Severity level
 *
 * This severity level can be specified for both console messages
 * and file messages. It allows to disable messages (i.e., OFF),
 * show only error messages (i.e. ERROR), show error and warning
 * messages (i.e. WARN) or show all messages (i.e. DEBUG).
 */
enum severity_level_t {
	OFF 	= 0, //< No logging messages
	ERROR	= 1, //< Only errors
	WARN	= 2, //< Errors and warnings
	DEBUG	= 3  //< Show all messages
};

namespace net {









/**
 * \brief Simple logger to log messages on file and console.
 *
 * This is the implementation of a simple logger in C++. It is implemented 
 * as a Singleton, so it can be easily called through two DEBUG macros.
 * It is Pthread-safe.
 * It allows to log on both file and screen, and to specify a severity level
 * for both.
 *
 * Example of configuration of the Logger: *
 * \code
 * 	DEBUG_CONF("outputfile", DEBUG, ERROR);
 * \endcode
 *
 * Example of usage of the Logger:
 * \code
 * 	DEBUG(DEBUG, "hello " << "world");
 * \endcode
 */
class Logger
{
	/* \brief Current severity level for logging on file.
	 *
	 * It can be OFF, DEBUG, WARN or ERROR.
	 */
	severity_level_t fileSeverityLevel_;

	/* \brief Current severity level for logging on screen.
	 *
	 * It can be OFF, DEBUG, WARN or ERROR.
	 */
	severity_level_t screenSeverityLevel_;

	/**
	 * \brief Lock for mutual exclusion between different threads
	 */
	static std::mutex lock_;
	
	/**
	 * \brief Pointer to the unique Logger (i.e., Singleton)
	 */
	static Logger* m_;

	/**
	 * \brief Initial part of the name of the file used for Logging.
	 * Date and time are automatically appended.
	 */
	std::string logFile_;

	/**
	 * \brief Stream used when logging on a file
	 */
	std::ofstream out_;

	/**
	 * \brief Initial time (used to print relative times)
	 */
	struct timeval initialTime_;

	/**
	 * \brief Debug: to know if the latest message has been printed
	 * on file.
	 */
	bool latestMsgPrintedOnFile_;

	/**
	 * \brief Debug: to know if the latest message has been printed 
	 * on screen.
	 */
	bool latestMsgPrintedOnScreen_;

	Logger();
	~Logger();

	/**
	 * \brief Method to lock in case of multithreading
	 */
	inline static void lock();

	/**
	 * \brief Method to unlock in case of multithreading
	 */
	inline static void unlock();

public:

	static Logger& getInstance();

	void print(const severity_level_t	severityLevel,
			const std::string&	sourceFile,
			const int 		codeLine,
			const std::string& 	message);

	void configure (const std::string&	outputFile,
			const severity_level_t	fileSeverityLevel,
			const severity_level_t	screenSeverityLevel);

	/**
	 * \brief Method to know if the latest message has been printed on file
	 * @return true if it has been printed; false otherwise
	 */
	inline bool latestMsgPrintedOnFile() const {
		return latestMsgPrintedOnFile_;
	}

	/**
	 * \brief Method to know if the latest message has been printed on file
	 * @return true if it has been printed; false otherwise
	 */
	inline bool latestMsgPrintedOnScreen() const {
		return latestMsgPrintedOnScreen_;
	}

};

} // logger

#endif // LOGGER_HPP_
