/*
 * Copyright (C) 2013 Evidence Srl - www.evidence.eu.com
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef PROTOCOL_HPP_
#define PROTOCOL_HPP_

namespace net {

enum class protocol_type {
	STREAM,
	DGRAM
};

enum class protocol_domain {
	LOCAL,
	IPv4
};

class protocol {
public:
	protocol (enum protocol_type type, 
	enum protocol_domain domain):
		type_{type}, domain_{domain}{}
	inline enum protocol_type getType() const
	{
		return type_;
	}
	inline enum protocol_domain getDomain() const
	{
		return domain_;
	}

	bool operator==(const protocol& p) const 
	{
		if ((type_ == p.type_) && (domain_ == p.domain_))
			return true;
		return false;
	}

	bool operator!=(const protocol& p) const 
	{
		if ((type_ == p.type_) && (domain_ == p.domain_))
			return false;
		return true;
	}

private:
	enum protocol_type type_;
	enum protocol_domain domain_;
};

static const net::protocol_type STREAM=net::protocol_type::STREAM;
static const net::protocol_type DGRAM=net::protocol_type::STREAM;
static const net::protocol_domain IPv4=net::protocol_domain::IPv4;
static const net::protocol_domain LOCAL=net::protocol_domain::LOCAL;

// #define TCP_IPv4 protocol{STREAM, IPv4}
// #define UDP_IPv4 protocol{DGRAM, IPv4}
// #define STREAM_LOCAL protocol{STREAM, LOCAL}
// #define DGRAM_LOCAL protocol{DGRAM, LOCAL}

}

#endif // PROTOCOL_HPP_

