/*
 * Copyright (C) 2013 Evidence Srl - www.evidence.eu.com
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef STREAM_LOCAL_HPP_
#define STREAM_LOCAL_HPP_

#include <stdexcept>

#include "abstract_socket.hpp"
#include "posix_socket.hpp"
#include "address.hpp"

namespace net {
namespace local {
namespace stream {

/// Address for local stream communications.
class address: public Address {
public:
	/**
	 * @brief Constructor
	 *
	 * @param addr std::string containing the path of the local socket
	 */
	address(const std::string& addr):
		address_{addr}{};

	/**
	 * @brief Get the path of the local socket
	 *
	 * @return a std::string containing the path of the local socket
	 */
	inline std::string getAddress() const {
		return address_;
	}
private:
	/// Path of the local socket:
	std::string address_;
};

/**
 * @brief Server for local stream communications.
 */
class server: public AbstractSocket {
public:
	/**
	 * @brief Constructor
	 *
	 * This constructor allocates a concrete class derived from net::AbstractSystemSocket.
	 * @param max_pending_connections Number of maximum allowed pending connections
	 */
	server(int max_pending_connections = 100):
	    AbstractSocket(new PosixSocket(protocol(STREAM, LOCAL))),
	    max_pending_connections_(max_pending_connections){}

	/**
	 * @brief Constructor to accept() a local stream connection on an existing socket.
	 *
	 * This constructor allocates a concrete class derived from net::AbstractSystemSocket
	 * and accept a local stream connection on the given (existing) local stream socket.
	 * @param srv Existing local stream socket on which the new connection must be accepted.
	 * @param max_pending_connections Number of maximum allowed pending connections
	 */
	server(AbstractSocket* srv, int max_pending_connections = 100):
	    AbstractSocket(new PosixSocket(protocol (STREAM, LOCAL))),
	    max_pending_connections_(max_pending_connections)
	{
		socket_->accept((srv->getSocket()));
	}

	/**
	 * @brief Method to bind the server to a local socket
	 *
	 * This method invokes the platform-specific bind() operation.
	 * @param addr Address (i.e., net::local::stream::address)
	 * containing the local path of the socket which the server must be bound to
	 */
	inline void bind (const Address& addr)
	{
		AbstractSocket::socket_->bind(addr);
	}
	
	/**
	 * @brief Listen operation
	 *
	 * This method invokes the platform-specific listen() operation.
	 * This method sets the number of maximum allowed pending connections.
	 */
	inline void listen()
	{
		AbstractSocket::socket_->listen(max_pending_connections_);
	}

	/**
	 * @brief Method to open the server on a certain socket
	 *
	 * This method calls net::local::stream::server::bind() and
	 * net::local::stream::server::listen(). They, in turn, call
	 * the platform-specific operations.
	 * @param addr Address (i.e., net::local::stream::address)
	 * containing the local path of the socket that must be open
	 */
	inline void open (const Address& addr)
	{
		bind (addr);
		listen();
	}

private:

	/// Number of maximum allowed pending connections
	int max_pending_connections_;
};



/**
 * @brief Client for local stream communications.
 */
class client: public AbstractSocket {
public:
	/**
	 * @brief Constructor
	 *
	 * This constructor allocates a concrete class
	 * derived from net::AbstractSystemSocket.
	 */
	client():
	    AbstractSocket(new PosixSocket(protocol (STREAM, LOCAL))){}

	/**
	 * @brief Method to connect the client to a certain local socket
	 *
	 * This method invokes the platform-specific connect() operation.
	 * @param addr Address (i.e., net::local::stream::address)
	 * containing the path of the local socket which the client must
	 * be connected to
	 */
	inline void connect (const Address& addr)
	{
		AbstractSocket::socket_->connect(addr);
	}

	/**
	 * @brief Method to open the client towards a certain address
	 *
	 * This method calls net::local::stream::connect(),
	 * which in turn invokes the platform-specific connect() operation.
	 * @param addr Address (i.e., net::local::stream::address)
	 * containing the path of the local socket which the client must
	 * open
	 */
	inline void open (const Address& addr)
	{
		connect (addr);
	}

};

}}} // net::local::stream

#endif // STREAM_LOCAL_HPP_
