/*
 * Copyright (C) 2013 Evidence Srl - www.evidence.eu.com
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef TCP_IPV4_HPP_
#define TCP_IPV4_HPP_

#include <stdexcept>

#include "abstract_socket.hpp"
#include "posix_socket.hpp"
#include "address.hpp"
#include "platform.hpp"

namespace net {
namespace ip4 {
namespace tcp {

/// Address for IPv4 TCP communications.
class address: public Address {
public:
	/**
	 * @brief Constructor
	 *
	 * @param addr std::string containing the address (e.g., "127.0.0.1")
	 * @param port Integer containing the port number (e.g., 1234)
	 */
	address(const std::string& addr, int port):
		address_{addr}, port_{port}{};
	
	/**
	 * @brief Get the address
	 *
	 * @return a std::string containing the IP address
	 * (not the port number)
	 */
	inline std::string getAddress() const {
		return address_;
	}

	/**
	 * @brief Get the port number
	 *
	 * @return an integer containing the port number
	 */
	inline int getPort() const {
		return port_;
	}

private:
	/// IP address
	std::string address_;
	
	/// Port number
	int port_;
};


/**
 * @brief Server for IPv4 TCP communications.
 */
class server: public AbstractSocket {
public:
	/**
	 * @brief Constructor
	 *
	 * This constructor allocates a concrete class derived from net::AbstractSystemSocket.
	 * @param max_pending_connections Number of maximum allowed pending connections
	 */
	server(int max_pending_connections = 100):
	    AbstractSocket(createSocket(protocol(protocol_type::STREAM,
	        protocol_domain::IPv4))), max_pending_connections_(max_pending_connections){}

	/**
	 * @brief Constructor to accept() a TCP connection on an existing socket.
	 *
	 * This constructor allocates a concrete class derived from net::AbstractSystemSocket
	 * and accept a TCP connection on the given (existing) TCP socket.
	 * @param srv Existing TCP socket on which the new connection must be accepted.
	 * @param max_pending_connections Number of maximum allowed pending connections
	 */
	server(AbstractSocket* srv, int max_pending_connections = 100):
	    AbstractSocket(createSocket(protocol(protocol_type::STREAM,
	        protocol_domain::IPv4))), max_pending_connections_(max_pending_connections)
	{
			socket_->accept((srv->getSocket()));
	}

	/**
	 * @brief Method to bind the server to an address
	 *
	 * This method invokes the platform-specific bind() operation.
	 * @param addr Address (i.e., net::ip4::tcp::address)
	 * which the server must be bound to
	 */
	inline void bind (const Address& addr){
		AbstractSocket::socket_->bind(addr);
	}

	/**
	 * @brief Listen operation
	 *
	 * This method sets the number of maximum allowed pending connections.
	 * This method invokes the platform-specific listen() operation.
	 */
	inline void listen(){
		AbstractSocket::socket_->listen(max_pending_connections_);
	}

	/**
	 * @brief Method to open the server towards a certain address
	 *
	 * This method calls net::ip4::tcp::server::bind() and
	 * net::ip4::tcp::server::listen(). They, in turn, call
	 * the platform-specific operations.
	 * @param addr Address (i.e., net::ip4::tcp::address) 
	 * that must be open by the server
	 */
	inline void open (const Address& addr) {
		bind (addr);
		listen();
	}

private:
	/// Number of maximum allowed pending connections
	int max_pending_connections_;
};



/**
 * @brief Client for IPv4 TCP communications.
 */
class client: public AbstractSocket {
public:
	/**
	 * @brief Constructor
	 *
	 * This constructor allocates a concrete class
	 * derived from net::AbstractSystemSocket.
	 */
	client():
	    AbstractSocket(createSocket(protocol(protocol_type::STREAM,
	        protocol_domain::IPv4))){}
	
	/**
	 * @brief Method to connect the client to an address
	 *
	 * This method invokes the platform-specific connect() operation.
	 * @param addr Address (i.e., net::ip4::tcp::address)
	 * which the client must be connected to
	 */
	inline void connect (const Address& addr){
		AbstractSocket::socket_->connect(addr);
	}

	/**
	 * @brief Method to open the client towards a certain address
	 *
	 * This method calls net::ip4::tcp::client::connect(),
	 * which in turn invokes the platform-specific connect() operation.
	 * @param addr Address (i.e., net::ip4::tcp::address) 
	 * that must be open by the client
	 */
	inline void open (const Address& addr) {
		connect(addr);
	}

};

}}} // net::ip4::tcp

#endif // TCP_IPV4_HPP_
